# Generated by Django 5.0.4 on 2024-05-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_remove_loanapplication_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age_range', models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36+', '36+')], max_length=10)),
                ('payment_choice', models.CharField(choices=[('cash', 'Cash Payment'), ('loan', 'Loan')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
    ]
