# Generated by Django 5.0.4 on 2024-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentapplication',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
